"""Add etudiant_matieres association table

Revision ID: 49e395b21214
Revises: 005
Create Date: 2025-11-24 15:57:27.194119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e395b21214'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etudiant_matieres',
    sa.Column('etudiant_id', sa.String(length=36), nullable=False),
    sa.Column('matiere_id', sa.String(length=36), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('est_actuelle', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id', 'matiere_id')
    )
    op.drop_index('ix_qcms_createur_id', table_name='qcms')
    op.drop_index('ix_qcms_status', table_name='qcms')
    op.create_foreign_key(None, 'qcms', 'matieres', ['matiere_id'], ['id'])
    op.drop_index('ix_questions_qcm_id', table_name='questions')
    op.drop_index('ix_questions_type', table_name='questions')
    op.drop_constraint('questions_qcm_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'qcms', ['qcm_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_qcm_id_fkey', 'questions', 'qcms', ['qcm_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_questions_type', 'questions', ['type_question'], unique=False)
    op.create_index('ix_questions_qcm_id', 'questions', ['qcm_id'], unique=False)
    op.drop_constraint(None, 'qcms', type_='foreignkey')
    op.create_index('ix_qcms_status', 'qcms', ['status'], unique=False)
    op.create_index('ix_qcms_createur_id', 'qcms', ['createur_id'], unique=False)
    op.drop_table('etudiant_matieres')
    # ### end Alembic commands ###



