"""Make session_id nullable in resultats table for free QCMs

Revision ID: 85d8a335ddf0
Revises: 49e395b21214
Create Date: 2025-11-24 17:18:19.547201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d8a335ddf0'
down_revision = '49e395b21214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resultats', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resultats', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###



