"""Ajout champs publication resultats

Revision ID: c0e190b74a6e
Revises: 007_refonte_enseignant_etudiant
Create Date: 2025-11-30 11:45:42.096943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0e190b74a6e'
down_revision = 'd30d724c69d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajout des colonnes de publication des résultats
    op.add_column('resultats', sa.Column('est_publie', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sessions_examen', sa.Column('resultats_publies', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Suppression des colonnes de publication des résultats
    op.drop_column('sessions_examen', 'resultats_publies')
    op.drop_column('resultats', 'est_publie')
    # ### end Alembic commands ###



