"""Initial migration

Revision ID: d30d724c69d2
Revises: 
Create Date: 2025-11-26 08:34:28.952351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30d724c69d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matieres',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('couleur', sa.String(length=7), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matieres_code'), 'matieres', ['code'], unique=True)
    op.create_table('niveaux',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.String(length=20), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niveaux_code'), 'niveaux', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('numero_etudiant', sa.String(length=50), nullable=True),
    sa.Column('numero_enseignant', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_numero_enseignant'), 'users', ['numero_enseignant'], unique=True)
    op.create_index(op.f('ix_users_numero_etudiant'), 'users', ['numero_etudiant'], unique=True)
    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('effectif_max', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('niveau_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_annee_scolaire'), 'classes', ['annee_scolaire'], unique=False)
    op.create_index(op.f('ix_classes_code'), 'classes', ['code'], unique=True)
    op.create_table('etudiant_matieres',
    sa.Column('etudiant_id', sa.String(length=36), nullable=False),
    sa.Column('matiere_id', sa.String(length=36), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('est_actuelle', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id', 'matiere_id')
    )
    op.create_table('etudiant_niveaux',
    sa.Column('etudiant_id', sa.String(length=36), nullable=False),
    sa.Column('niveau_id', sa.String(length=36), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('est_actuel', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id', 'niveau_id')
    )
    op.create_table('professeur_matieres',
    sa.Column('professeur_id', sa.String(length=36), nullable=False),
    sa.Column('matiere_id', sa.String(length=36), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('professeur_id', 'matiere_id')
    )
    op.create_table('professeur_niveaux',
    sa.Column('professeur_id', sa.String(length=36), nullable=False),
    sa.Column('niveau_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('professeur_id', 'niveau_id')
    )
    op.create_table('qcms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duree', sa.Integer(), nullable=True),
    sa.Column('matiere', sa.String(length=100), nullable=True),
    sa.Column('matiere_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('est_public', sa.Boolean(), nullable=False),
    sa.Column('createur_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['createur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qcms_matiere_id'), 'qcms', ['matiere_id'], unique=False)
    op.create_table('etudiant_classes',
    sa.Column('etudiant_id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('est_actuelle', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id', 'classe_id')
    )
    op.create_table('professeur_classes',
    sa.Column('professeur_id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('matiere_id', sa.String(length=36), nullable=True),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('professeur_id', 'classe_id')
    )
    op.create_table('qcm_niveaux',
    sa.Column('qcm_id', sa.String(length=36), nullable=False),
    sa.Column('niveau_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.ForeignKeyConstraint(['qcm_id'], ['qcms.id'], ),
    sa.PrimaryKeyConstraint('qcm_id', 'niveau_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enonce', sa.Text(), nullable=False),
    sa.Column('type_question', sa.String(length=20), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('reponse_correcte', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('explication', sa.Text(), nullable=True),
    sa.Column('qcm_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qcm_id'], ['qcms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions_examen',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('tentatives_max', sa.Integer(), nullable=False),
    sa.Column('melange_questions', sa.Boolean(), nullable=False),
    sa.Column('melange_options', sa.Boolean(), nullable=False),
    sa.Column('afficher_correction', sa.Boolean(), nullable=False),
    sa.Column('note_passage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qcm_id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=True),
    sa.Column('createur_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['createur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qcm_id'], ['qcms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_examen_date_debut'), 'sessions_examen', ['date_debut'], unique=False)
    op.create_index(op.f('ix_sessions_examen_date_fin'), 'sessions_examen', ['date_fin'], unique=False)
    op.create_table('resultats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('etudiant_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('qcm_id', sa.String(length=36), nullable=False),
    sa.Column('numero_tentative', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('duree_reelle_secondes', sa.Integer(), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('score_maximum', sa.Float(), nullable=False),
    sa.Column('note_sur_20', sa.Float(), nullable=True),
    sa.Column('pourcentage', sa.Float(), nullable=True),
    sa.Column('questions_total', sa.Integer(), nullable=False),
    sa.Column('questions_repondues', sa.Integer(), nullable=False),
    sa.Column('questions_correctes', sa.Integer(), nullable=False),
    sa.Column('questions_incorrectes', sa.Integer(), nullable=False),
    sa.Column('questions_partielles', sa.Integer(), nullable=False),
    sa.Column('reponses_detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('est_reussi', sa.Boolean(), nullable=False),
    sa.Column('est_valide', sa.Boolean(), nullable=False),
    sa.Column('feedback_auto', sa.Text(), nullable=True),
    sa.Column('commentaire_prof', sa.Text(), nullable=True),
    sa.Column('note_prof', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qcm_id'], ['qcms.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_examen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultats_etudiant_id'), 'resultats', ['etudiant_id'], unique=False)
    op.create_index(op.f('ix_resultats_qcm_id'), 'resultats', ['qcm_id'], unique=False)
    op.create_index(op.f('ix_resultats_session_id'), 'resultats', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultats_session_id'), table_name='resultats')
    op.drop_index(op.f('ix_resultats_qcm_id'), table_name='resultats')
    op.drop_index(op.f('ix_resultats_etudiant_id'), table_name='resultats')
    op.drop_table('resultats')
    op.drop_index(op.f('ix_sessions_examen_date_fin'), table_name='sessions_examen')
    op.drop_index(op.f('ix_sessions_examen_date_debut'), table_name='sessions_examen')
    op.drop_table('sessions_examen')
    op.drop_table('questions')
    op.drop_table('qcm_niveaux')
    op.drop_table('professeur_classes')
    op.drop_table('etudiant_classes')
    op.drop_index(op.f('ix_qcms_matiere_id'), table_name='qcms')
    op.drop_table('qcms')
    op.drop_table('professeur_niveaux')
    op.drop_table('professeur_matieres')
    op.drop_table('etudiant_niveaux')
    op.drop_table('etudiant_matieres')
    op.drop_index(op.f('ix_classes_code'), table_name='classes')
    op.drop_index(op.f('ix_classes_annee_scolaire'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_users_numero_etudiant'), table_name='users')
    op.drop_index(op.f('ix_users_numero_enseignant'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_niveaux_code'), table_name='niveaux')
    op.drop_table('niveaux')
    op.drop_index(op.f('ix_matieres_code'), table_name='matieres')
    op.drop_table('matieres')
    # ### end Alembic commands ###



